site_name: PopcornFX for Warcraft III
site_url: https://wiselencave.github.io/war3-pfx-docs
site_description: Tutorials and documentation for using PopcornFX 2.5 in Warcraft III Reforged
site_author: wiselencave
repo_url: https://github.com/wiselencave/war3-pfx-docs
repo_name: wiselencave/war3-pfx-docs

theme:
  name: material
  language: en
  palette:
    - scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - attr_list
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - References:
    - Overview: reference/index.md
    - "PopcornAssetBaker basics": reference/assetbaker_basics.md
    - "Runtime Attributes": reference/attributes.md
    - "Simulation Interfaces": reference/hasteleported_SI.md
    - "PopcornFX File Extensions": reference/extensions.md
